
services:

    # https://symfony.com/doc/current/bundles/KnpMenuBundle/menu_builder_service.html
    app.menu_builder:
        class: App\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu
    